// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJtI5CxG-aBXnYvzQFJFnuzGftjC6AXnY',
    appId: '1:270293532686:android:482a882a5771c150747c5f',
    messagingSenderId: '270293532686',
    projectId: 'notesapp-3163b',
    storageBucket: 'notesapp-3163b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu-SMGLKcZQhZgjbb-6hvoXavofpKkABw',
    appId: '1:270293532686:ios:b5b06e54333b9889747c5f',
    messagingSenderId: '270293532686',
    projectId: 'notesapp-3163b',
    storageBucket: 'notesapp-3163b.firebasestorage.app',
    androidClientId: '270293532686-vi27lndmr75gum9g3o83q3bmda6vgo19.apps.googleusercontent.com',
    iosClientId: '270293532686-i07c1q45ro8lf68ocu6ahg1ip5d3r5ai.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesAppFirebase',
  );

}